{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-labelled
  version: {{ version|replace("-", "_") }}

source:
  fn: labelled_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/labelled_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/labelled/labelled_{{ version }}.tar.gz
  sha256: 2a1eec22db648065ac06376d49d2973314619bcb0d308f79a31e4e2a38613f70

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, questionr
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-dplyr
    - r-haven >=1.0.0

  run:
    - r-base
    - r-dplyr
    - r-haven >=1.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('labelled')"           # [not win]
    - "\"%R%\" -e \"library('labelled')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/larmarange/labelled
  license: GPL-3
  summary: Work with labelled data imported from 'SPSS' or 'Stata' with 'haven' or 'foreign'.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: labelled
# Type: Package
# Title: Manipulating Labelled Data
# Version: 1.1.0
# Date: 2018-05-24
# Maintainer: Joseph Larmarange <joseph@larmarange.net>
# Authors@R: c( person("Joseph", "Larmarange", email = "joseph@larmarange.net", role = c("aut", "cre")), person("Daniel", "Ludecke", role = "ctb"), person("Hadley", "Wickham", role = "ctb"), person("Bojanowski", "Micha", role = "ctb") )
# Description: Work with labelled data imported from 'SPSS' or 'Stata' with 'haven' or 'foreign'.
# License: GPL-3
# Encoding: UTF-8
# Imports: haven (>= 1.0.0), dplyr, stats
# Suggests: testthat, knitr, questionr
# Enhances: memisc
# LazyData: true
# URL: https://github.com/larmarange/labelled
# BugReports: https://github.com/larmarange/labelled/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-05-24 17:34:33 UTC; Larmarange
# Author: Joseph Larmarange [aut, cre], Daniel Ludecke [ctb], Hadley Wickham [ctb], Bojanowski Micha [ctb]
# Repository: CRAN
# Date/Publication: 2018-05-24 18:41:16 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
